// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import {
  isLikelySupabaseTransactionPooler,
  isPostgresConnectionString,
  pickFirstPostgresUrl,
} from "./src/lib/database-url";

function prismaConfigDatasourceUrl(): string {
  const explicit = process.env["DATABASE_URL"]?.trim();
  if (isPostgresConnectionString(explicit)) return explicit!;

  return (
    pickFirstPostgresUrl(
      process.env["SUPABASE_DATABASE_URL"],
      process.env["NEXT_PUBLIC_SUPABASE_DATABASE_URL"],
      process.env["POSTGRES_PRISMA_URL"],
      process.env["POSTGRES_URL"],
    ) ?? ""
  );
}

function prismaConfigDirectUrl(): string {
  const direct = process.env["DIRECT_URL"]?.trim();
  if (isPostgresConnectionString(direct)) return direct!;

  const main = prismaConfigDatasourceUrl();
  if (isPostgresConnectionString(main) && !isLikelySupabaseTransactionPooler(main)) {
    return main;
  }

  return direct ?? "";
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: prismaConfigDatasourceUrl(),
    directUrl: prismaConfigDirectUrl(),
  },
});
