// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Netlify / Supabase often expose SUPABASE_DATABASE_URL; local dev uses DATABASE_URL in .env
    url:
      process.env["DATABASE_URL"]?.trim() ||
      process.env["SUPABASE_DATABASE_URL"]?.trim() ||
      "",
  },
});
